"""Anveshar engine: the five stage pipeline that assembles a report.

run() loads curated, cited knowledge for a condition, optionally personalizes it with
a patient's molecular profile and single-cell expression, appends the hypothesis
hypotheses, validates that nothing contains a forbidden dash, and (optionally) renders
the HTML report. It degrades honestly: an unknown condition raises rather than inventing.
"""
from __future__ import annotations
import os
import re
import json
from .schema import (DiseaseReport, Target, Therapy, Tier, Modality, PatientProfile,
                     assert_no_dashes)

EXAMPLES = os.path.join(os.path.dirname(os.path.dirname(__file__)), "examples")

# Curated, cited knowledge bases available in this build. Add a json under examples/ to extend.
SLUGS = {
    "renal medullary carcinoma": "renal_medullary.json",
    "rmc": "renal_medullary.json",
    "rectal neuroendocrine tumor": "rectal_net.json",
    "rectal net": "rectal_net.json",
    "spinal muscular atrophy": "rare_disease/spinal_muscular_atrophy.json",
    "sma": "rare_disease/spinal_muscular_atrophy.json",
    "chordoma": "chordoma.json",
    "adenoid cystic carcinoma": "adenoid_cystic_carcinoma.json",
    "alveolar soft part sarcoma": "alveolar_soft_part_sarcoma.json",
    "atypical teratoid rhabdoid tumor": "atrt.json",
    "atrt": "atrt.json",
    "ewing sarcoma": "ewing_sarcoma.json",
    "uveal melanoma": "uveal_melanoma.json",
    "nut carcinoma": "nut_carcinoma.json",
    "duchenne muscular dystrophy": "rare_disease/duchenne_muscular_dystrophy.json",
    "dmd": "rare_disease/duchenne_muscular_dystrophy.json",
    "cystic fibrosis": "rare_disease/cystic_fibrosis.json",
    "cf": "rare_disease/cystic_fibrosis.json",
    "sickle cell disease": "rare_disease/sickle_cell_disease.json",
    "scd": "rare_disease/sickle_cell_disease.json",
    "rpe65 retinal dystrophy": "rare_disease/rpe65_retinal_dystrophy.json",
    "leber congenital amaurosis": "rare_disease/rpe65_retinal_dystrophy.json",
    "hereditary attr amyloidosis": "rare_disease/hereditary_attr_amyloidosis.json",
    "hattr": "rare_disease/hereditary_attr_amyloidosis.json",
    "gaucher disease": "rare_disease/gaucher_disease.json",
    "huntington disease": "rare_disease/huntington_disease.json",
}

DISCOVERY_INTRO = {
    "patient": "Where the proven options run out, Anveshar proposes new ideas to test. "
               "These are research hypotheses, not treatments, generated by reasoning across "
               "cancers that share the same biology. Each names an experiment that could confirm or rule it out.",
    "clinician": "Computationally generated cross-condition hypotheses that no dedicated trial has "
                 "yet tested in this cancer, each graded by transferability and paired with a falsifiable prediction. "
                 "Kept separate from approved options; for research and molecular tumor board discussion only.",
    "researcher": "The discovery layer reasons over shared molecular dependencies to nominate therapies and "
                  "advanced modalities (including cell, radioligand, antisense, and gene directed strategies) by "
                  "analogy from mechanistically related conditions, each with a testable prediction.",
}


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")


def _load_curated(cancer: str) -> dict | None:
    """Find a curated knowledge file by explicit alias or by slug (adding a condition is
    as simple as dropping a <slug>.json into examples/ or examples/rare_disease/)."""
    candidates = []
    alias = SLUGS.get(cancer.strip().lower())
    if alias:
        candidates.append(alias)
    s = _slug(cancer)
    candidates += [f"{s}.json", f"rare_disease/{s}.json"]
    for f in candidates:
        p = os.path.join(EXAMPLES, f)
        if os.path.exists(p):
            data = json.load(open(p, encoding="utf-8"))
            stem = os.path.splitext(os.path.basename(f))[0]
            wf = os.path.join(EXAMPLES, "workflows", stem + ".json")
            if os.path.exists(wf):
                data.setdefault("workflow", json.load(open(wf, encoding="utf-8")))
            return data
    return None


def _light_report(data: dict) -> DiseaseReport:
    """A partial DiseaseReport (name, targets, therapies) sufficient for discovery and matching."""
    def tier(x):
        try:
            return Tier(str(x.get("tier", 3)))
        except ValueError:
            return Tier.T3

    def modality(x):
        try:
            return Modality(x.get("modality", "other"))
        except ValueError:
            return Modality.OTHER

    return DiseaseReport(
        name=data.get("cancer", {}).get("name", ""),
        targets=[Target(t.get("name", ""), t.get("present_in", ""), t.get("evidence", ""))
                 for t in data.get("targets", [])],
        therapies=[Therapy(drug=x.get("drug", ""), target=x.get("target", ""), tier=tier(x),
                           modality=modality(x)) for x in data.get("therapies", [])],
    )


def _patient_render_dict(profile: PatientProfile) -> dict:
    return DiseaseReport(name="x", patient=profile).to_render_dict().get("patient")


def _live_assemble(condition: str, model: str | None = None) -> dict:
    """Assemble a report for an uncurated condition via the connectors plus the Claude API."""
    from .evidence import pubmed, clinicaltrials
    from . import llm
    evidence = {"pubmed": pubmed.search(condition, retmax=15),
                "trials": [t.__dict__ for t in clinicaltrials.search(condition)]}
    return llm.synthesize_report(condition, evidence, model=model or llm.DEFAULT_MODEL)


def _attach_workflow(data):
    """Attach a generated comp-bio workflow when the report has no curated one.

    Resolves the condition in the rare cancer catalog and builds a bespoke, driver class
    tailored workflow. Silently skips conditions not in the catalog (for example rare diseases),
    so a curated workflow is never overwritten and a missing catalog match is not an error.
    """
    if data.get("workflow"):
        return
    try:
        from .pipeline import resolve as _resolve, translate as _translate
        from .workflow import generate as _generate
        rr = _resolve(data.get("cancer", {}).get("name", ""))
        if rr:
            data["workflow"] = _generate(rr, _translate(rr))
    except Exception:
        pass


def run(cancer: str, profile=None, scrna: str | None = None, discovery: bool = True,
        out: str | None = None, live: bool = False, model: str | None = None) -> dict:
    """Assemble (and optionally render) a Anveshar report for `cancer`.

    profile: a raw profile dict or a path to one (examples/profiles/*.json shape).
    scrna:   path to an .h5ad; expressed druggable targets are read out and added.
    discovery: append the cross-condition hypotheses.
    out:     if given, write the HTML report there.
    Returns the DATA dict the template renders.
    """
    data = _load_curated(cancer)
    if data is None:
        if live:
            data = _live_assemble(cancer, model)
        else:
            raise ValueError(
                f"No curated Anveshar knowledge for '{cancer}'. "
                f"Available: {sorted(set(SLUGS))}. Pass live=True (needs ANTHROPIC_API_KEY) to "
                f"assemble it from the evidence connectors via the Claude API.")
    rep = _light_report(data)

    prof_obj: PatientProfile | None = None
    if profile is not None:
        from .variants.interpret import interpret_profile
        raw = profile if isinstance(profile, dict) else json.load(open(profile, encoding="utf-8"))
        prof_obj = interpret_profile(raw)

    if scrna:
        from .expression.scrna import extract_targets
        expr = extract_targets(scrna)
        if prof_obj is None:
            prof_obj = PatientProfile(present=True, tumor_summary="Single cell expression profile", summary={})
        prof_obj.alterations = list(prof_obj.alterations) + list(expr)

    if prof_obj is not None:
        data["patient"] = _patient_render_dict(prof_obj)

    if not discovery:
        # explicit opt-out hides the novelty section even when curated hypotheses exist
        data.pop("discovery", None); data.pop("discoveryIntro", None)
    elif not data.get("discovery"):
        # curated discovery in the knowledge base wins; only generate when none is present
        from .translation.discovery import generate
        hyps = generate(rep, prof_obj)
        if hyps:
            data["discovery"] = DiseaseReport(name=data["cancer"]["name"], discovery=hyps).to_render_dict()["discovery"]
    if data.get("discovery"):
        data.setdefault("discoveryIntro", DISCOVERY_INTRO)

    _attach_workflow(data)
    assert_no_dashes(data)
    if out:
        from .report.render import render_data
        render_data(data, out)
    return data


def run_file(path: str, out: str | None = None, discovery: bool = True) -> dict:
    """Render a specific curated example file directly (robust to the display name), loading
    its co-located workflow and appending discovery hypotheses where none are curated."""
    data = json.load(open(path, encoding="utf-8"))
    stem = os.path.splitext(os.path.basename(path))[0]
    wf = os.path.join(EXAMPLES, "workflows", stem + ".json")
    if os.path.exists(wf):
        data.setdefault("workflow", json.load(open(wf, encoding="utf-8")))
    rep = _light_report(data)
    if not discovery:
        data.pop("discovery", None); data.pop("discoveryIntro", None)
    elif not data.get("discovery"):
        from .translation.discovery import generate
        hyps = generate(rep, None)
        if hyps:
            data["discovery"] = DiseaseReport(name=data["cancer"]["name"], discovery=hyps).to_render_dict()["discovery"]
    if data.get("discovery"):
        data.setdefault("discoveryIntro", DISCOVERY_INTRO)
    _attach_workflow(data)
    assert_no_dashes(data)
    if out:
        from .report.render import render_data
        render_data(data, out)
    return data
